#!/usr/bin/env ruby

# David Selassie
# April 28, 2011

# USAGE: cute CMD
# Enqueues a command to be executed by cuted.

require 'trollop'
require 'drb'

config = {'server_uri' => 'druby://localhost:1987'}

# If we have the environment variable, use that instead.
config['server_uri'] = ENV['cuted_server'] if ENV['cuted_server']

options = Trollop::options do
  opt :dir, 'run command in a dir other than the CWD', :default => Dir.pwd
  opt :weight, 'weight of this command', :default => 1
  opt :priority, 'priority of this command', :default => 0
  opt :server, 'server to submit commands to', :type => :string, :default => config['server_uri']
end
Trollop::die 'cute: You must specify a command' if ARGV.length < 1

# Join together the rest of the arguments as the command.
cmd = ARGV.join(' ')

begin
  DRb.start_service
  queue = DRbObject.new(nil, options[:server])

  # Get the real command stored in the queue.
  cmd = queue.push_cmd(cmd)

  # Set up attributes.
  cmd.dir = options[:dir]
  cmd.priority = options[:priority]
  cmd.weight = options[:weight]

  # Try to run tasks.
  queue.work

  puts "Command '#{cmd}' submitted"
rescue DRb::DRbConnError => err
  puts "Could not connect to '#{options[:server]}'"

  exit 1
end
