#!/usr/bin/env ruby

# David Selassie
# April 28, 2011

# USAGE: cute CMD
# Enqueues a command to be executed by cuted.

require 'trollop'

# Setup the default server pipe path that might be overwritten.
config = {'server_pipe' => File.expand_path('~/.cuted.sock')}

# If we have the environment variable, use that instead.
config['server_pipe'] = ENV['cuted_pipe'] if ENV['cuted_pipe']

options = Trollop::options do
  opt :dir, 'run command in a dir other than the CWD', :default => Dir.pwd
  opt :threads, 'number of threads this process will use', :default => 1
  opt :pipe, 'server pipe to submit commands to', :default => config['server_pipe']
end
Trollop::die 'cute: You must specify a command' if ARGV.length < 1

# Join together the rest of the arguments as the command.
cmd = ARGV.join(' ')

# Make sure the server is runing by checking to see if the pipe is real.
if not File.pipe?(options[:pipe])
  STDERR.puts 'cute: Can not find cuted pipe at '#{options[:pipe]}'; did not execute command'
  exit -1
end

File.open(options[:pipe], 'w') do |cmd_pipe|
  cmd_pipe.puts("#{cmd}\x00#{options[:dir]}\x00#{options[:threads]}")
end
